// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: epochs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEpoch = `-- name: CreateEpoch :exec
INSERT INTO e2ee_epochs (id, thread_id, sender_id, recipient_id, bootstrap)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEpochParams struct {
	ID          pgtype.UUID
	ThreadID    int64
	SenderID    int64
	RecipientID int64
	Bootstrap   string
}

func (q *Queries) CreateEpoch(ctx context.Context, arg CreateEpochParams) error {
	_, err := q.db.Exec(ctx, createEpoch,
		arg.ID,
		arg.ThreadID,
		arg.SenderID,
		arg.RecipientID,
		arg.Bootstrap,
	)
	return err
}

const getEpochForUser = `-- name: GetEpochForUser :one
SELECT e.id, t.external_id AS thread_external_id,
       sender.external_id AS sender_external_id, recipient.external_id AS recipient_external_id,
       e.bootstrap, b.key_backup
FROM e2ee_epochs AS e
JOIN threads AS t ON t.id = e.thread_id
JOIN users AS sender ON sender.id = e.sender_id
JOIN users AS recipient ON recipient.id = e.recipient_id
LEFT JOIN e2ee_epoch_backups AS b ON b.epoch_id = e.id AND b.user_id = $1
WHERE e.id = $2 AND e.thread_id = $3
`

type GetEpochForUserParams struct {
	UserID   int64
	EpochID  pgtype.UUID
	ThreadID int64
}

type GetEpochForUserRow struct {
	ID                  pgtype.UUID
	ThreadExternalID    pgtype.UUID
	SenderExternalID    pgtype.UUID
	RecipientExternalID pgtype.UUID
	Bootstrap           string
	KeyBackup           []byte
}

func (q *Queries) GetEpochForUser(ctx context.Context, arg GetEpochForUserParams) (GetEpochForUserRow, error) {
	row := q.db.QueryRow(ctx, getEpochForUser, arg.UserID, arg.EpochID, arg.ThreadID)
	var i GetEpochForUserRow
	err := row.Scan(
		&i.ID,
		&i.ThreadExternalID,
		&i.SenderExternalID,
		&i.RecipientExternalID,
		&i.Bootstrap,
		&i.KeyBackup,
	)
	return i, err
}

const getEpochIdentity = `-- name: GetEpochIdentity :one
SELECT id FROM e2ee_epochs WHERE id = $1 AND thread_id = $2
`

type GetEpochIdentityParams struct {
	EpochID  pgtype.UUID
	ThreadID int64
}

func (q *Queries) GetEpochIdentity(ctx context.Context, arg GetEpochIdentityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEpochIdentity, arg.EpochID, arg.ThreadID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEpochParticipantProfiles = `-- name: GetEpochParticipantProfiles :many
SELECT u.id, u.external_id, u.public_bundle
FROM participants AS p JOIN users AS u ON u.id = p.user_id
WHERE p.thread_id = $1 AND p.left_seq IS NULL ORDER BY u.id
`

type GetEpochParticipantProfilesRow struct {
	ID           int64
	ExternalID   pgtype.UUID
	PublicBundle []byte
}

func (q *Queries) GetEpochParticipantProfiles(ctx context.Context, threadID int64) ([]GetEpochParticipantProfilesRow, error) {
	rows, err := q.db.Query(ctx, getEpochParticipantProfiles, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpochParticipantProfilesRow
	for rows.Next() {
		var i GetEpochParticipantProfilesRow
		if err := rows.Scan(&i.ID, &i.ExternalID, &i.PublicBundle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpochThreadForParticipant = `-- name: GetEpochThreadForParticipant :one
SELECT t.id, t.kind, t.current_epoch_id
FROM threads AS t JOIN participants AS p ON p.thread_id = t.id
WHERE t.external_id = $1
  AND p.user_id = $2 AND p.left_seq IS NULL
`

type GetEpochThreadForParticipantParams struct {
	ThreadExternalID pgtype.UUID
	UserID           int64
}

type GetEpochThreadForParticipantRow struct {
	ID             int64
	Kind           string
	CurrentEpochID pgtype.UUID
}

func (q *Queries) GetEpochThreadForParticipant(ctx context.Context, arg GetEpochThreadForParticipantParams) (GetEpochThreadForParticipantRow, error) {
	row := q.db.QueryRow(ctx, getEpochThreadForParticipant, arg.ThreadExternalID, arg.UserID)
	var i GetEpochThreadForParticipantRow
	err := row.Scan(&i.ID, &i.Kind, &i.CurrentEpochID)
	return i, err
}

const listEpochsForUser = `-- name: ListEpochsForUser :many
SELECT e.id, t.external_id AS thread_external_id,
       sender.external_id AS sender_external_id, recipient.external_id AS recipient_external_id,
       e.bootstrap, b.key_backup
FROM e2ee_epochs AS e
JOIN threads AS t ON t.id = e.thread_id
JOIN users AS sender ON sender.id = e.sender_id
JOIN users AS recipient ON recipient.id = e.recipient_id
LEFT JOIN e2ee_epoch_backups AS b ON b.epoch_id = e.id AND b.user_id = $1
WHERE e.thread_id = $2 ORDER BY e.created_at, e.id
`

type ListEpochsForUserParams struct {
	UserID   int64
	ThreadID int64
}

type ListEpochsForUserRow struct {
	ID                  pgtype.UUID
	ThreadExternalID    pgtype.UUID
	SenderExternalID    pgtype.UUID
	RecipientExternalID pgtype.UUID
	Bootstrap           string
	KeyBackup           []byte
}

func (q *Queries) ListEpochsForUser(ctx context.Context, arg ListEpochsForUserParams) ([]ListEpochsForUserRow, error) {
	rows, err := q.db.Query(ctx, listEpochsForUser, arg.UserID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpochsForUserRow
	for rows.Next() {
		var i ListEpochsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadExternalID,
			&i.SenderExternalID,
			&i.RecipientExternalID,
			&i.Bootstrap,
			&i.KeyBackup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEpochThreadForParticipant = `-- name: LockEpochThreadForParticipant :one
SELECT t.id, t.kind, t.current_epoch_id
FROM threads AS t JOIN participants AS p ON p.thread_id = t.id
WHERE t.external_id = $1
  AND p.user_id = $2 AND p.left_seq IS NULL
FOR UPDATE OF t
`

type LockEpochThreadForParticipantParams struct {
	ThreadExternalID pgtype.UUID
	UserID           int64
}

type LockEpochThreadForParticipantRow struct {
	ID             int64
	Kind           string
	CurrentEpochID pgtype.UUID
}

func (q *Queries) LockEpochThreadForParticipant(ctx context.Context, arg LockEpochThreadForParticipantParams) (LockEpochThreadForParticipantRow, error) {
	row := q.db.QueryRow(ctx, lockEpochThreadForParticipant, arg.ThreadExternalID, arg.UserID)
	var i LockEpochThreadForParticipantRow
	err := row.Scan(&i.ID, &i.Kind, &i.CurrentEpochID)
	return i, err
}

const setCurrentEpoch = `-- name: SetCurrentEpoch :exec
UPDATE threads SET current_epoch_id = $1 WHERE id = $2
`

type SetCurrentEpochParams struct {
	EpochID  pgtype.UUID
	ThreadID int64
}

func (q *Queries) SetCurrentEpoch(ctx context.Context, arg SetCurrentEpochParams) error {
	_, err := q.db.Exec(ctx, setCurrentEpoch, arg.EpochID, arg.ThreadID)
	return err
}

const storeEpochBackup = `-- name: StoreEpochBackup :exec
INSERT INTO e2ee_epoch_backups (epoch_id, user_id, key_backup)
VALUES ($1, $2, $3)
ON CONFLICT (epoch_id, user_id) DO NOTHING
`

type StoreEpochBackupParams struct {
	EpochID   pgtype.UUID
	UserID    int64
	KeyBackup []byte
}

func (q *Queries) StoreEpochBackup(ctx context.Context, arg StoreEpochBackupParams) error {
	_, err := q.db.Exec(ctx, storeEpochBackup, arg.EpochID, arg.UserID, arg.KeyBackup)
	return err
}
