// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveGroupMembers = `-- name: CountActiveGroupMembers :one
SELECT COUNT(*) AS members,
       COUNT(*) FILTER (WHERE role = 'admin') AS admins
FROM participants
WHERE thread_id = $1 AND left_seq IS NULL
`

type CountActiveGroupMembersRow struct {
	Members int64
	Admins  int64
}

func (q *Queries) CountActiveGroupMembers(ctx context.Context, threadID int64) (CountActiveGroupMembersRow, error) {
	row := q.db.QueryRow(ctx, countActiveGroupMembers, threadID)
	var i CountActiveGroupMembersRow
	err := row.Scan(&i.Members, &i.Admins)
	return i, err
}

const createGroupParticipant = `-- name: CreateGroupParticipant :exec
INSERT INTO participants (thread_id, user_id, role, joined_seq, last_read_seq)
VALUES ($1, $2, $3,
        $4, $4::BIGINT - 1)
`

type CreateGroupParticipantParams struct {
	ThreadID  int64
	UserID    int64
	Role      string
	JoinedSeq int64
}

func (q *Queries) CreateGroupParticipant(ctx context.Context, arg CreateGroupParticipantParams) error {
	_, err := q.db.Exec(ctx, createGroupParticipant,
		arg.ThreadID,
		arg.UserID,
		arg.Role,
		arg.JoinedSeq,
	)
	return err
}

const createGroupThread = `-- name: CreateGroupThread :one
INSERT INTO threads (kind, name, created_by)
VALUES ('group', $1, $2)
RETURNING id, external_id
`

type CreateGroupThreadParams struct {
	Name      pgtype.Text
	CreatedBy int64
}

type CreateGroupThreadRow struct {
	ID         int64
	ExternalID pgtype.UUID
}

func (q *Queries) CreateGroupThread(ctx context.Context, arg CreateGroupThreadParams) (CreateGroupThreadRow, error) {
	row := q.db.QueryRow(ctx, createGroupThread, arg.Name, arg.CreatedBy)
	var i CreateGroupThreadRow
	err := row.Scan(&i.ID, &i.ExternalID)
	return i, err
}

const createSystemMessage = `-- name: CreateSystemMessage :one
WITH created AS (
    INSERT INTO messages (thread_id, sender_id, seq, kind, content_format, content)
    VALUES ($1, $2, $3,
            'system', 'plaintext', $4)
    RETURNING id, external_id, thread_id, sender_id, seq, kind,
              content_format, content, created_at
)
SELECT created.id, created.external_id, thread.external_id AS thread_external_id, thread.kind AS thread_kind,
       sender.external_id AS sender_external_id, created.seq, created.kind,
       created.content_format, created.content, created.created_at
FROM created
JOIN threads AS thread ON thread.id = created.thread_id
JOIN users AS sender ON sender.id = created.sender_id
`

type CreateSystemMessageParams struct {
	ThreadID int64
	SenderID int64
	Seq      int64
	Content  string
}

type CreateSystemMessageRow struct {
	ID               int64
	ExternalID       pgtype.UUID
	ThreadExternalID pgtype.UUID
	ThreadKind       string
	SenderExternalID pgtype.UUID
	Seq              int64
	Kind             string
	ContentFormat    string
	Content          string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateSystemMessage(ctx context.Context, arg CreateSystemMessageParams) (CreateSystemMessageRow, error) {
	row := q.db.QueryRow(ctx, createSystemMessage,
		arg.ThreadID,
		arg.SenderID,
		arg.Seq,
		arg.Content,
	)
	var i CreateSystemMessageRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ThreadExternalID,
		&i.ThreadKind,
		&i.SenderExternalID,
		&i.Seq,
		&i.Kind,
		&i.ContentFormat,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const endParticipant = `-- name: EndParticipant :exec
UPDATE participants
SET left_seq = $1, left_at = NOW()
WHERE id = $2 AND left_seq IS NULL
`

type EndParticipantParams struct {
	LeftSeq pgtype.Int8
	ID      int64
}

func (q *Queries) EndParticipant(ctx context.Context, arg EndParticipantParams) error {
	_, err := q.db.Exec(ctx, endParticipant, arg.LeftSeq, arg.ID)
	return err
}

const getActiveParticipant = `-- name: GetActiveParticipant :one
SELECT id, role, joined_seq, last_read_seq
FROM participants
WHERE thread_id = $1
  AND user_id = $2 AND left_seq IS NULL
`

type GetActiveParticipantParams struct {
	ThreadID int64
	UserID   int64
}

type GetActiveParticipantRow struct {
	ID          int64
	Role        string
	JoinedSeq   int64
	LastReadSeq int64
}

func (q *Queries) GetActiveParticipant(ctx context.Context, arg GetActiveParticipantParams) (GetActiveParticipantRow, error) {
	row := q.db.QueryRow(ctx, getActiveParticipant, arg.ThreadID, arg.UserID)
	var i GetActiveParticipantRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.JoinedSeq,
		&i.LastReadSeq,
	)
	return i, err
}

const getLatestMembership = `-- name: GetLatestMembership :one
SELECT id, joined_seq, left_seq
FROM participants
WHERE thread_id = $1 AND user_id = $2
ORDER BY joined_seq DESC
LIMIT 1
`

type GetLatestMembershipParams struct {
	ThreadID int64
	UserID   int64
}

type GetLatestMembershipRow struct {
	ID        int64
	JoinedSeq int64
	LeftSeq   pgtype.Int8
}

func (q *Queries) GetLatestMembership(ctx context.Context, arg GetLatestMembershipParams) (GetLatestMembershipRow, error) {
	row := q.db.QueryRow(ctx, getLatestMembership, arg.ThreadID, arg.UserID)
	var i GetLatestMembershipRow
	err := row.Scan(&i.ID, &i.JoinedSeq, &i.LeftSeq)
	return i, err
}

const getThreadMessageAtSequence = `-- name: GetThreadMessageAtSequence :one
SELECT m.id, m.external_id, t.external_id AS thread_external_id, t.kind AS thread_kind,
       sender.external_id AS sender_external_id, m.seq, m.kind,
       m.content_format, m.content, m.created_at
FROM messages AS m
JOIN threads AS t ON t.id = m.thread_id
JOIN users AS sender ON sender.id = m.sender_id
WHERE m.thread_id = $1 AND m.seq = $2
`

type GetThreadMessageAtSequenceParams struct {
	ThreadID int64
	Seq      int64
}

type GetThreadMessageAtSequenceRow struct {
	ID               int64
	ExternalID       pgtype.UUID
	ThreadExternalID pgtype.UUID
	ThreadKind       string
	SenderExternalID pgtype.UUID
	Seq              int64
	Kind             string
	ContentFormat    string
	Content          string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetThreadMessageAtSequence(ctx context.Context, arg GetThreadMessageAtSequenceParams) (GetThreadMessageAtSequenceRow, error) {
	row := q.db.QueryRow(ctx, getThreadMessageAtSequence, arg.ThreadID, arg.Seq)
	var i GetThreadMessageAtSequenceRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ThreadExternalID,
		&i.ThreadKind,
		&i.SenderExternalID,
		&i.Seq,
		&i.Kind,
		&i.ContentFormat,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT member.external_id, member.username, participant.role,
       participant.joined_seq, participant.last_read_seq
FROM participants AS participant
JOIN users AS member ON member.id = participant.user_id
WHERE participant.thread_id = $1
  AND participant.left_seq IS NULL
  AND EXISTS (SELECT 1 FROM participants AS actor
              WHERE actor.thread_id = participant.thread_id
                AND actor.user_id = $2 AND actor.left_seq IS NULL)
ORDER BY participant.role, member.username, member.id
`

type ListGroupMembersParams struct {
	ThreadID int64
	ActorID  int64
}

type ListGroupMembersRow struct {
	ExternalID  pgtype.UUID
	Username    string
	Role        string
	JoinedSeq   int64
	LastReadSeq int64
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.ThreadID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.Username,
			&i.Role,
			&i.JoinedSeq,
			&i.LastReadSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockThreadByExternalID = `-- name: LockThreadByExternalID :one
SELECT id, external_id, kind, last_seq
FROM threads
WHERE external_id = $1
FOR UPDATE
`

type LockThreadByExternalIDRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Kind       string
	LastSeq    int64
}

func (q *Queries) LockThreadByExternalID(ctx context.Context, threadExternalID pgtype.UUID) (LockThreadByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, lockThreadByExternalID, threadExternalID)
	var i LockThreadByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Kind,
		&i.LastSeq,
	)
	return i, err
}

const promoteOldestGroupMember = `-- name: PromoteOldestGroupMember :one
WITH promoted AS (
    UPDATE participants SET role = 'admin'
    WHERE id = (
        SELECT member.id FROM participants AS member
        WHERE member.thread_id = $1 AND member.left_seq IS NULL
        ORDER BY member.joined_seq, member.user_id LIMIT 1
    )
    RETURNING user_id
)
SELECT username FROM users JOIN promoted ON promoted.user_id = users.id
`

func (q *Queries) PromoteOldestGroupMember(ctx context.Context, threadID int64) (string, error) {
	row := q.db.QueryRow(ctx, promoteOldestGroupMember, threadID)
	var username string
	err := row.Scan(&username)
	return username, err
}
