// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createThreadMessage = `-- name: CreateThreadMessage :one
WITH created AS (
    INSERT INTO messages (
        external_id,
        thread_id,
        sender_id,
        seq,
        kind,
        content_format,
        content
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        'text',
        $5,
        $6
    )
    RETURNING id, external_id, thread_id, sender_id, seq,
              kind, content_format, content, created_at
)
SELECT
    created.id,
    created.external_id,
    thread.external_id AS thread_external_id,
    thread.kind AS thread_kind,
    sender.external_id AS sender_external_id,
    created.seq,
    created.kind,
    created.content_format,
    created.content,
    created.created_at
FROM created
JOIN threads AS thread ON thread.id = created.thread_id
JOIN users AS sender ON sender.id = created.sender_id
`

type CreateThreadMessageParams struct {
	MessageExternalID pgtype.UUID
	ThreadID          int64
	SenderID          int64
	Seq               int64
	ContentFormat     string
	Content           string
}

type CreateThreadMessageRow struct {
	ID               int64
	ExternalID       pgtype.UUID
	ThreadExternalID pgtype.UUID
	ThreadKind       string
	SenderExternalID pgtype.UUID
	Seq              int64
	Kind             string
	ContentFormat    string
	Content          string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateThreadMessage(ctx context.Context, arg CreateThreadMessageParams) (CreateThreadMessageRow, error) {
	row := q.db.QueryRow(ctx, createThreadMessage,
		arg.MessageExternalID,
		arg.ThreadID,
		arg.SenderID,
		arg.Seq,
		arg.ContentFormat,
		arg.Content,
	)
	var i CreateThreadMessageRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ThreadExternalID,
		&i.ThreadKind,
		&i.SenderExternalID,
		&i.Seq,
		&i.Kind,
		&i.ContentFormat,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getE2EEMessageParticipants = `-- name: GetE2EEMessageParticipants :many
SELECT member.id, member.external_id, member.identity_public_key
FROM participants AS participant
JOIN users AS member ON member.id = participant.user_id
WHERE participant.thread_id = $1 AND participant.left_seq IS NULL
ORDER BY member.id
`

type GetE2EEMessageParticipantsRow struct {
	ID                int64
	ExternalID        pgtype.UUID
	IdentityPublicKey []byte
}

func (q *Queries) GetE2EEMessageParticipants(ctx context.Context, threadID int64) ([]GetE2EEMessageParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getE2EEMessageParticipants, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetE2EEMessageParticipantsRow
	for rows.Next() {
		var i GetE2EEMessageParticipantsRow
		if err := rows.Scan(&i.ID, &i.ExternalID, &i.IdentityPublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembershipVersion = `-- name: GetMembershipVersion :one
SELECT COALESCE(MAX(boundary.seq), 0)::BIGINT AS version
FROM participants AS participant
JOIN threads AS thread ON thread.id = participant.thread_id
CROSS JOIN LATERAL (VALUES (participant.joined_seq), (participant.left_seq + 1)) AS boundary(seq)
WHERE thread.external_id = $1
  AND boundary.seq <= $2::BIGINT
`

type GetMembershipVersionParams struct {
	ThreadExternalID pgtype.UUID
	Seq              int64
}

// A removal includes its system message; the snapshot changes at left_seq + 1.
// Resolve after commit at the message seq, for both direct and group messages.
func (q *Queries) GetMembershipVersion(ctx context.Context, arg GetMembershipVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMembershipVersion, arg.ThreadExternalID, arg.Seq)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getMessageByExternalID = `-- name: GetMessageByExternalID :one
SELECT
    m.id,
    m.external_id,
    m.thread_id,
    m.sender_id,
    t.external_id AS thread_external_id,
    t.kind AS thread_kind,
    sender.external_id AS sender_external_id,
    m.seq,
    m.kind,
    m.content_format,
    m.content,
    m.created_at
FROM messages AS m
JOIN threads AS t ON t.id = m.thread_id
JOIN users AS sender ON sender.id = m.sender_id
WHERE m.external_id = $1
`

type GetMessageByExternalIDRow struct {
	ID               int64
	ExternalID       pgtype.UUID
	ThreadID         int64
	SenderID         int64
	ThreadExternalID pgtype.UUID
	ThreadKind       string
	SenderExternalID pgtype.UUID
	Seq              int64
	Kind             string
	ContentFormat    string
	Content          string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMessageByExternalID(ctx context.Context, messageExternalID pgtype.UUID) (GetMessageByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByExternalID, messageExternalID)
	var i GetMessageByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ThreadID,
		&i.SenderID,
		&i.ThreadExternalID,
		&i.ThreadKind,
		&i.SenderExternalID,
		&i.Seq,
		&i.Kind,
		&i.ContentFormat,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadHistoryAccess = `-- name: GetThreadHistoryAccess :one
SELECT t.id
FROM threads AS t
JOIN participants AS p
  ON p.thread_id = t.id
 AND p.user_id = $1
WHERE t.external_id = $2
LIMIT 1
`

type GetThreadHistoryAccessParams struct {
	UserID           int64
	ThreadExternalID pgtype.UUID
}

func (q *Queries) GetThreadHistoryAccess(ctx context.Context, arg GetThreadHistoryAccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, getThreadHistoryAccess, arg.UserID, arg.ThreadExternalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const incrementThreadSequence = `-- name: IncrementThreadSequence :one
UPDATE threads
SET last_seq = last_seq + 1
WHERE id = $1
RETURNING last_seq
`

func (q *Queries) IncrementThreadSequence(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, incrementThreadSequence, id)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const listMemberIDsAtSequence = `-- name: ListMemberIDsAtSequence :many
SELECT DISTINCT member.external_id
FROM participants AS participant
JOIN threads AS thread ON thread.id = participant.thread_id
JOIN users AS member ON member.id = participant.user_id
WHERE thread.external_id = $1
  AND participant.joined_seq <= $2::BIGINT
  AND (participant.left_seq IS NULL OR participant.left_seq >= $2::BIGINT)
ORDER BY member.external_id
`

type ListMemberIDsAtSequenceParams struct {
	ThreadExternalID pgtype.UUID
	Seq              int64
}

func (q *Queries) ListMemberIDsAtSequence(ctx context.Context, arg ListMemberIDsAtSequenceParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMemberIDsAtSequence, arg.ThreadExternalID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var external_id pgtype.UUID
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesPage = `-- name: ListThreadMessagesPage :many
SELECT
    m.id,
    m.external_id,
    t.external_id AS thread_external_id,
    t.kind AS thread_kind,
    sender.external_id AS sender_external_id,
    m.seq,
    m.kind,
    m.content_format,
    m.content,
    m.created_at
FROM messages AS m
JOIN threads AS t ON t.id = m.thread_id
JOIN users AS sender ON sender.id = m.sender_id
WHERE t.external_id = $1
  AND EXISTS (
    SELECT 1 FROM participants AS participant
    WHERE participant.thread_id = t.id
      AND participant.user_id = $2
      AND m.seq >= participant.joined_seq
      AND (participant.left_seq IS NULL OR m.seq <= participant.left_seq)
  )
  AND (
    $3::BIGINT IS NULL
    OR m.seq < $3
  )
ORDER BY m.seq DESC
LIMIT $4::INTEGER + 1
`

type ListThreadMessagesPageParams struct {
	ThreadExternalID pgtype.UUID
	UserID           int64
	BeforeSeq        pgtype.Int8
	PageSize         int32
}

type ListThreadMessagesPageRow struct {
	ID               int64
	ExternalID       pgtype.UUID
	ThreadExternalID pgtype.UUID
	ThreadKind       string
	SenderExternalID pgtype.UUID
	Seq              int64
	Kind             string
	ContentFormat    string
	Content          string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListThreadMessagesPage(ctx context.Context, arg ListThreadMessagesPageParams) ([]ListThreadMessagesPageRow, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesPage,
		arg.ThreadExternalID,
		arg.UserID,
		arg.BeforeSeq,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadMessagesPageRow
	for rows.Next() {
		var i ListThreadMessagesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.ThreadExternalID,
			&i.ThreadKind,
			&i.SenderExternalID,
			&i.Seq,
			&i.Kind,
			&i.ContentFormat,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockThreadForParticipant = `-- name: LockThreadForParticipant :one
SELECT t.id, t.kind, t.encryption_mode
FROM threads AS t
JOIN participants AS p
  ON p.thread_id = t.id
 AND p.user_id = $1
 AND p.left_seq IS NULL
WHERE t.external_id = $2
FOR UPDATE OF t
`

type LockThreadForParticipantParams struct {
	UserID           int64
	ThreadExternalID pgtype.UUID
}

type LockThreadForParticipantRow struct {
	ID             int64
	Kind           string
	EncryptionMode string
}

func (q *Queries) LockThreadForParticipant(ctx context.Context, arg LockThreadForParticipantParams) (LockThreadForParticipantRow, error) {
	row := q.db.QueryRow(ctx, lockThreadForParticipant, arg.UserID, arg.ThreadExternalID)
	var i LockThreadForParticipantRow
	err := row.Scan(&i.ID, &i.Kind, &i.EncryptionMode)
	return i, err
}

const threadExistsByExternalID = `-- name: ThreadExistsByExternalID :one
SELECT EXISTS (
    SELECT 1 FROM threads WHERE external_id = $1
)
`

func (q *Queries) ThreadExistsByExternalID(ctx context.Context, externalID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, threadExistsByExternalID, externalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
