// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
WITH created AS (
    INSERT INTO messages (sender_id, receiver_id, content)
    VALUES ($1, $2, $3)
    RETURNING id, external_id, sender_id, receiver_id, content, created_at
)
SELECT
    created.id,
    created.external_id,
    sender.external_id AS sender_external_id,
    receiver.external_id AS receiver_external_id,
    created.content,
    created.created_at
FROM created
JOIN users AS sender ON sender.id = created.sender_id
JOIN users AS receiver ON receiver.id = created.receiver_id
`

type CreateMessageParams struct {
	SenderID   int64
	ReceiverID int64
	Content    string
}

type CreateMessageRow struct {
	ID                 int64
	ExternalID         pgtype.UUID
	SenderExternalID   pgtype.UUID
	ReceiverExternalID pgtype.UUID
	Content            string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.SenderID, arg.ReceiverID, arg.Content)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.SenderExternalID,
		&i.ReceiverExternalID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesBetween = `-- name: ListMessagesBetween :many
SELECT
    recent.id,
    recent.external_id,
    sender.external_id AS sender_external_id,
    receiver.external_id AS receiver_external_id,
    recent.content,
    recent.created_at
FROM (
    SELECT id, external_id, sender_id, receiver_id, content, created_at
    FROM messages
    WHERE
        (sender_id = $1 AND receiver_id = $2)
        OR
        (sender_id = $2 AND receiver_id = $1)
    ORDER BY id DESC
    LIMIT 100
) AS recent
JOIN users AS sender ON sender.id = recent.sender_id
JOIN users AS receiver ON receiver.id = recent.receiver_id
ORDER BY recent.id
`

type ListMessagesBetweenParams struct {
	UserOneID int64
	UserTwoID int64
}

type ListMessagesBetweenRow struct {
	ID                 int64
	ExternalID         pgtype.UUID
	SenderExternalID   pgtype.UUID
	ReceiverExternalID pgtype.UUID
	Content            string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListMessagesBetween(ctx context.Context, arg ListMessagesBetweenParams) ([]ListMessagesBetweenRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBetween, arg.UserOneID, arg.UserTwoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBetweenRow
	for rows.Next() {
		var i ListMessagesBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.SenderExternalID,
			&i.ReceiverExternalID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
