// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID         int64
	ExternalID pgtype.UUID
	SenderID   int64
	ReceiverID int64
	Content    string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID         int64
	ExternalID pgtype.UUID
	Username   string
	CreatedAt  pgtype.Timestamptz
}
