// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type E2eeEpoch struct {
	ID          pgtype.UUID
	ThreadID    int64
	SenderID    int64
	RecipientID int64
	Bootstrap   string
	CreatedAt   pgtype.Timestamptz
}

type E2eeEpochBackup struct {
	EpochID   pgtype.UUID
	UserID    int64
	KeyBackup []byte
}

type Message struct {
	ID            int64
	ExternalID    pgtype.UUID
	ThreadID      int64
	SenderID      int64
	Seq           int64
	Kind          string
	ContentFormat string
	Content       string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	EpochID       pgtype.UUID
}

type Participant struct {
	ID          int64
	ThreadID    int64
	UserID      int64
	Role        string
	JoinedSeq   int64
	LeftSeq     pgtype.Int8
	LastReadSeq int64
	JoinedAt    pgtype.Timestamptz
	LeftAt      pgtype.Timestamptz
}

type Prekey struct {
	ID        int64
	UserID    int64
	KeyID     int64
	PublicKey []byte
	CreatedAt pgtype.Timestamptz
}

type Thread struct {
	ID             int64
	ExternalID     pgtype.UUID
	Kind           string
	Name           pgtype.Text
	CreatedBy      int64
	LastSeq        int64
	CreatedAt      pgtype.Timestamptz
	CurrentEpochID pgtype.UUID
}

type User struct {
	ID                 int64
	ExternalID         pgtype.UUID
	Username           string
	CreatedAt          pgtype.Timestamptz
	AuthCredentialHash string
	Kdf                []byte
	PublicBundle       []byte
	AccountVault       []byte
}
