// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prekeys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeE2EEOneTimePrekey = `-- name: ConsumeE2EEOneTimePrekey :one
DELETE FROM prekeys AS consumed
WHERE consumed.id = (
    SELECT candidate.id FROM prekeys AS candidate
    WHERE candidate.user_id = $1
    ORDER BY candidate.key_id LIMIT 1
)
RETURNING consumed.key_id, consumed.public_key
`

type ConsumeE2EEOneTimePrekeyRow struct {
	KeyID     int64
	PublicKey []byte
}

func (q *Queries) ConsumeE2EEOneTimePrekey(ctx context.Context, userID int64) (ConsumeE2EEOneTimePrekeyRow, error) {
	row := q.db.QueryRow(ctx, consumeE2EEOneTimePrekey, userID)
	var i ConsumeE2EEOneTimePrekeyRow
	err := row.Scan(&i.KeyID, &i.PublicKey)
	return i, err
}

const getE2EEClaimParticipants = `-- name: GetE2EEClaimParticipants :many
SELECT user_id FROM participants
WHERE thread_id = $1 AND left_seq IS NULL ORDER BY user_id FOR SHARE
`

func (q *Queries) GetE2EEClaimParticipants(ctx context.Context, threadID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getE2EEClaimParticipants, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getE2EEClaimThread = `-- name: GetE2EEClaimThread :one
SELECT id, kind FROM threads WHERE external_id = $1 FOR SHARE
`

type GetE2EEClaimThreadRow struct {
	ID   int64
	Kind string
}

func (q *Queries) GetE2EEClaimThread(ctx context.Context, externalID pgtype.UUID) (GetE2EEClaimThreadRow, error) {
	row := q.db.QueryRow(ctx, getE2EEClaimThread, externalID)
	var i GetE2EEClaimThreadRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const insertE2EEOneTimePrekey = `-- name: InsertE2EEOneTimePrekey :exec
INSERT INTO prekeys (user_id, key_id, public_key)
VALUES ($1, $2, $3)
`

type InsertE2EEOneTimePrekeyParams struct {
	UserID    int64
	KeyID     int64
	PublicKey []byte
}

func (q *Queries) InsertE2EEOneTimePrekey(ctx context.Context, arg InsertE2EEOneTimePrekeyParams) error {
	_, err := q.db.Exec(ctx, insertE2EEOneTimePrekey, arg.UserID, arg.KeyID, arg.PublicKey)
	return err
}

const lockE2EEUser = `-- name: LockE2EEUser :one
SELECT id, external_id, public_bundle FROM users WHERE id = $1 FOR UPDATE
`

type LockE2EEUserRow struct {
	ID           int64
	ExternalID   pgtype.UUID
	PublicBundle []byte
}

func (q *Queries) LockE2EEUser(ctx context.Context, id int64) (LockE2EEUserRow, error) {
	row := q.db.QueryRow(ctx, lockE2EEUser, id)
	var i LockE2EEUserRow
	err := row.Scan(&i.ID, &i.ExternalID, &i.PublicBundle)
	return i, err
}
