// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectThread = `-- name: CreateDirectThread :one
INSERT INTO threads (kind, created_by)
VALUES ('direct', $1)
RETURNING id, external_id
`

type CreateDirectThreadRow struct {
	ID         int64
	ExternalID pgtype.UUID
}

func (q *Queries) CreateDirectThread(ctx context.Context, createdBy int64) (CreateDirectThreadRow, error) {
	row := q.db.QueryRow(ctx, createDirectThread, createdBy)
	var i CreateDirectThreadRow
	err := row.Scan(&i.ID, &i.ExternalID)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participants (thread_id, user_id, role, joined_seq, last_read_seq)
VALUES ($1, $2, 'member', 1, 0)
`

type CreateParticipantParams struct {
	ThreadID int64
	UserID   int64
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.Exec(ctx, createParticipant, arg.ThreadID, arg.UserID)
	return err
}

const getDirectThreadByParticipants = `-- name: GetDirectThreadByParticipants :one
SELECT thread.external_id
FROM threads AS thread
JOIN participants AS participant
  ON participant.thread_id = thread.id
 AND participant.left_seq IS NULL
WHERE thread.kind = 'direct'
GROUP BY thread.id
HAVING COUNT(*) = 2
   AND MIN(participant.user_id) = $1
   AND MAX(participant.user_id) = $2
ORDER BY thread.id
LIMIT 1
`

type GetDirectThreadByParticipantsParams struct {
	UserLowID  int64
	UserHighID int64
}

func (q *Queries) GetDirectThreadByParticipants(ctx context.Context, arg GetDirectThreadByParticipantsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectThreadByParticipants, arg.UserLowID, arg.UserHighID)
	var external_id pgtype.UUID
	err := row.Scan(&external_id)
	return external_id, err
}

const getThreadSummaryForUser = `-- name: GetThreadSummaryForUser :one
SELECT
    t.id, t.external_id, t.kind, COALESCE(t.name, '') AS name,
    mine.role,
    COALESCE(peer.external_id, '00000000-0000-0000-0000-000000000000'::UUID) AS peer_external_id,
    COALESCE(peer.username, '') AS peer_username,
    t.last_seq, mine.joined_seq, mine.last_read_seq,
    COALESCE(other.last_read_seq, 0)::BIGINT AS peer_last_read_seq,
    (SELECT COUNT(*) FROM participants AS member
     WHERE member.thread_id = t.id AND member.left_seq IS NULL) AS member_count,
    (SELECT COUNT(*) FROM messages AS unread_message
     WHERE unread_message.thread_id = t.id
       AND unread_message.seq >= mine.joined_seq
       AND unread_message.seq > mine.last_read_seq
       AND unread_message.sender_id <> mine.user_id) AS unread_count,
    last_message.seq AS last_message_seq,
    last_sender.external_id AS last_message_sender_external_id,
    last_message.content AS last_message_content,
    last_message.created_at AS last_message_created_at,
    t.created_at
FROM threads AS t
JOIN participants AS mine
  ON mine.thread_id = t.id
 AND mine.user_id = $1
 AND mine.left_seq IS NULL
LEFT JOIN participants AS other
  ON t.kind = 'direct'
 AND other.thread_id = t.id
 AND other.user_id <> mine.user_id
 AND other.left_seq IS NULL
LEFT JOIN users AS peer ON peer.id = other.user_id
LEFT JOIN messages AS last_message
  ON last_message.thread_id = t.id AND last_message.seq = t.last_seq
LEFT JOIN users AS last_sender ON last_sender.id = last_message.sender_id
WHERE t.external_id = $2
`

type GetThreadSummaryForUserParams struct {
	UserID           int64
	ThreadExternalID pgtype.UUID
}

type GetThreadSummaryForUserRow struct {
	ID                          int64
	ExternalID                  pgtype.UUID
	Kind                        string
	Name                        string
	Role                        string
	PeerExternalID              pgtype.UUID
	PeerUsername                string
	LastSeq                     int64
	JoinedSeq                   int64
	LastReadSeq                 int64
	PeerLastReadSeq             int64
	MemberCount                 int64
	UnreadCount                 int64
	LastMessageSeq              pgtype.Int8
	LastMessageSenderExternalID pgtype.UUID
	LastMessageContent          pgtype.Text
	LastMessageCreatedAt        pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) GetThreadSummaryForUser(ctx context.Context, arg GetThreadSummaryForUserParams) (GetThreadSummaryForUserRow, error) {
	row := q.db.QueryRow(ctx, getThreadSummaryForUser, arg.UserID, arg.ThreadExternalID)
	var i GetThreadSummaryForUserRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Kind,
		&i.Name,
		&i.Role,
		&i.PeerExternalID,
		&i.PeerUsername,
		&i.LastSeq,
		&i.JoinedSeq,
		&i.LastReadSeq,
		&i.PeerLastReadSeq,
		&i.MemberCount,
		&i.UnreadCount,
		&i.LastMessageSeq,
		&i.LastMessageSenderExternalID,
		&i.LastMessageContent,
		&i.LastMessageCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT
    t.id, t.external_id, t.kind, COALESCE(t.name, '') AS name,
    mine.role,
    COALESCE(peer.external_id, '00000000-0000-0000-0000-000000000000'::UUID) AS peer_external_id,
    COALESCE(peer.username, '') AS peer_username,
    t.last_seq, mine.joined_seq, mine.last_read_seq,
    COALESCE(other.last_read_seq, 0)::BIGINT AS peer_last_read_seq,
    (SELECT COUNT(*) FROM participants AS member
     WHERE member.thread_id = t.id AND member.left_seq IS NULL) AS member_count,
    (SELECT COUNT(*) FROM messages AS unread_message
     WHERE unread_message.thread_id = t.id
       AND unread_message.seq >= mine.joined_seq
       AND unread_message.seq > mine.last_read_seq
       AND unread_message.sender_id <> mine.user_id) AS unread_count,
    last_message.seq AS last_message_seq,
    last_sender.external_id AS last_message_sender_external_id,
    last_message.content AS last_message_content,
    last_message.created_at AS last_message_created_at,
    t.created_at
FROM threads AS t
JOIN participants AS mine
  ON mine.thread_id = t.id
 AND mine.user_id = $1
 AND mine.left_seq IS NULL
LEFT JOIN participants AS other
  ON t.kind = 'direct'
 AND other.thread_id = t.id
 AND other.user_id <> mine.user_id
 AND other.left_seq IS NULL
LEFT JOIN users AS peer ON peer.id = other.user_id
LEFT JOIN messages AS last_message
  ON last_message.thread_id = t.id AND last_message.seq = t.last_seq
LEFT JOIN users AS last_sender ON last_sender.id = last_message.sender_id
ORDER BY COALESCE(last_message.created_at, t.created_at) DESC, t.id DESC
`

type ListThreadsForUserRow struct {
	ID                          int64
	ExternalID                  pgtype.UUID
	Kind                        string
	Name                        string
	Role                        string
	PeerExternalID              pgtype.UUID
	PeerUsername                string
	LastSeq                     int64
	JoinedSeq                   int64
	LastReadSeq                 int64
	PeerLastReadSeq             int64
	MemberCount                 int64
	UnreadCount                 int64
	LastMessageSeq              pgtype.Int8
	LastMessageSenderExternalID pgtype.UUID
	LastMessageContent          pgtype.Text
	LastMessageCreatedAt        pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) ListThreadsForUser(ctx context.Context, userID int64) ([]ListThreadsForUserRow, error) {
	rows, err := q.db.Query(ctx, listThreadsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsForUserRow
	for rows.Next() {
		var i ListThreadsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Kind,
			&i.Name,
			&i.Role,
			&i.PeerExternalID,
			&i.PeerUsername,
			&i.LastSeq,
			&i.JoinedSeq,
			&i.LastReadSeq,
			&i.PeerLastReadSeq,
			&i.MemberCount,
			&i.UnreadCount,
			&i.LastMessageSeq,
			&i.LastMessageSenderExternalID,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUsersForDirectThread = `-- name: LockUsersForDirectThread :many
SELECT id, external_id, public_bundle
FROM users
WHERE id IN ($1, $2)
ORDER BY id
FOR UPDATE
`

type LockUsersForDirectThreadParams struct {
	UserLowID  int64
	UserHighID int64
}

type LockUsersForDirectThreadRow struct {
	ID           int64
	ExternalID   pgtype.UUID
	PublicBundle []byte
}

func (q *Queries) LockUsersForDirectThread(ctx context.Context, arg LockUsersForDirectThreadParams) ([]LockUsersForDirectThreadRow, error) {
	rows, err := q.db.Query(ctx, lockUsersForDirectThread, arg.UserLowID, arg.UserHighID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockUsersForDirectThreadRow
	for rows.Next() {
		var i LockUsersForDirectThreadRow
		if err := rows.Scan(&i.ID, &i.ExternalID, &i.PublicBundle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThreadRead = `-- name: MarkThreadRead :one
UPDATE participants AS participant
SET last_read_seq = GREATEST(participant.last_read_seq, $1)
FROM threads AS thread
WHERE participant.thread_id = thread.id
  AND participant.user_id = $2
  AND participant.left_seq IS NULL
  AND thread.external_id = $3
  AND $1 >= participant.joined_seq - 1
  AND $1 <= thread.last_seq
RETURNING participant.last_read_seq
`

type MarkThreadReadParams struct {
	LastReadSeq      int64
	UserID           int64
	ThreadExternalID pgtype.UUID
}

func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) (int64, error) {
	row := q.db.QueryRow(ctx, markThreadRead, arg.LastReadSeq, arg.UserID, arg.ThreadExternalID)
	var last_read_seq int64
	err := row.Scan(&last_read_seq)
	return last_read_seq, err
}
