// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectThread = `-- name: CreateDirectThread :one
INSERT INTO threads (
    kind, created_by, direct_user_low_id, direct_user_high_id, encryption_mode
)
VALUES (
    'direct', $1, $2,
    $3, 'plaintext'
)
ON CONFLICT (direct_user_low_id, direct_user_high_id) WHERE kind = 'direct'
DO NOTHING
RETURNING id, external_id, kind, last_seq, created_at
`

type CreateDirectThreadParams struct {
	CreatedBy        int64
	DirectUserLowID  pgtype.Int8
	DirectUserHighID pgtype.Int8
}

type CreateDirectThreadRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Kind       string
	LastSeq    int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateDirectThread(ctx context.Context, arg CreateDirectThreadParams) (CreateDirectThreadRow, error) {
	row := q.db.QueryRow(ctx, createDirectThread, arg.CreatedBy, arg.DirectUserLowID, arg.DirectUserHighID)
	var i CreateDirectThreadRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Kind,
		&i.LastSeq,
		&i.CreatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participants (thread_id, user_id, role, joined_seq, last_read_seq)
VALUES ($1, $2, 'member', 1, 0)
`

type CreateParticipantParams struct {
	ThreadID int64
	UserID   int64
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.Exec(ctx, createParticipant, arg.ThreadID, arg.UserID)
	return err
}

const getDirectThreadByPair = `-- name: GetDirectThreadByPair :one
SELECT id, external_id, kind, last_seq, created_at
FROM threads
WHERE kind = 'direct'
  AND direct_user_low_id = $1
  AND direct_user_high_id = $2
`

type GetDirectThreadByPairParams struct {
	DirectUserLowID  pgtype.Int8
	DirectUserHighID pgtype.Int8
}

type GetDirectThreadByPairRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Kind       string
	LastSeq    int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetDirectThreadByPair(ctx context.Context, arg GetDirectThreadByPairParams) (GetDirectThreadByPairRow, error) {
	row := q.db.QueryRow(ctx, getDirectThreadByPair, arg.DirectUserLowID, arg.DirectUserHighID)
	var i GetDirectThreadByPairRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Kind,
		&i.LastSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadSummaryForUser = `-- name: GetThreadSummaryForUser :one
SELECT
    t.id,
    t.external_id,
    t.kind,
    peer.external_id AS peer_external_id,
    peer.username AS peer_username,
    t.last_seq,
    last_message.seq AS last_message_seq,
    last_sender.external_id AS last_message_sender_external_id,
    last_message.content AS last_message_content,
    last_message.created_at AS last_message_created_at,
    t.created_at
FROM threads AS t
JOIN participants AS mine
  ON mine.thread_id = t.id
 AND mine.user_id = $1
 AND mine.left_seq IS NULL
JOIN participants AS other
  ON other.thread_id = t.id
 AND other.user_id <> mine.user_id
 AND other.left_seq IS NULL
JOIN users AS peer ON peer.id = other.user_id
LEFT JOIN messages AS last_message
  ON last_message.thread_id = t.id
 AND last_message.seq = t.last_seq
LEFT JOIN users AS last_sender ON last_sender.id = last_message.sender_id
WHERE t.external_id = $2
  AND t.kind = 'direct'
`

type GetThreadSummaryForUserParams struct {
	UserID           int64
	ThreadExternalID pgtype.UUID
}

type GetThreadSummaryForUserRow struct {
	ID                          int64
	ExternalID                  pgtype.UUID
	Kind                        string
	PeerExternalID              pgtype.UUID
	PeerUsername                string
	LastSeq                     int64
	LastMessageSeq              pgtype.Int8
	LastMessageSenderExternalID pgtype.UUID
	LastMessageContent          pgtype.Text
	LastMessageCreatedAt        pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) GetThreadSummaryForUser(ctx context.Context, arg GetThreadSummaryForUserParams) (GetThreadSummaryForUserRow, error) {
	row := q.db.QueryRow(ctx, getThreadSummaryForUser, arg.UserID, arg.ThreadExternalID)
	var i GetThreadSummaryForUserRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Kind,
		&i.PeerExternalID,
		&i.PeerUsername,
		&i.LastSeq,
		&i.LastMessageSeq,
		&i.LastMessageSenderExternalID,
		&i.LastMessageContent,
		&i.LastMessageCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT
    t.id,
    t.external_id,
    t.kind,
    peer.external_id AS peer_external_id,
    peer.username AS peer_username,
    t.last_seq,
    last_message.seq AS last_message_seq,
    last_sender.external_id AS last_message_sender_external_id,
    last_message.content AS last_message_content,
    last_message.created_at AS last_message_created_at,
    t.created_at
FROM participants AS mine
JOIN threads AS t ON t.id = mine.thread_id
JOIN participants AS other
  ON other.thread_id = t.id
 AND other.user_id <> mine.user_id
 AND other.left_seq IS NULL
JOIN users AS peer ON peer.id = other.user_id
LEFT JOIN messages AS last_message
  ON last_message.thread_id = t.id
 AND last_message.seq = t.last_seq
LEFT JOIN users AS last_sender ON last_sender.id = last_message.sender_id
WHERE mine.user_id = $1
  AND mine.left_seq IS NULL
  AND t.kind = 'direct'
ORDER BY COALESCE(last_message.created_at, t.created_at) DESC, t.id DESC
`

type ListThreadsForUserRow struct {
	ID                          int64
	ExternalID                  pgtype.UUID
	Kind                        string
	PeerExternalID              pgtype.UUID
	PeerUsername                string
	LastSeq                     int64
	LastMessageSeq              pgtype.Int8
	LastMessageSenderExternalID pgtype.UUID
	LastMessageContent          pgtype.Text
	LastMessageCreatedAt        pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) ListThreadsForUser(ctx context.Context, userID int64) ([]ListThreadsForUserRow, error) {
	rows, err := q.db.Query(ctx, listThreadsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsForUserRow
	for rows.Next() {
		var i ListThreadsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Kind,
			&i.PeerExternalID,
			&i.PeerUsername,
			&i.LastSeq,
			&i.LastMessageSeq,
			&i.LastMessageSenderExternalID,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
