// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO users (username, auth_credential_hash, kdf, public_bundle, account_vault)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, external_id, username, created_at
`

type CreateUserAccountParams struct {
	Username           string
	AuthCredentialHash string
	Kdf                []byte
	PublicBundle       []byte
	AccountVault       []byte
}

type CreateUserAccountRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Username   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (CreateUserAccountRow, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.Username,
		arg.AuthCredentialHash,
		arg.Kdf,
		arg.PublicBundle,
		arg.AccountVault,
	)
	var i CreateUserAccountRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthParamsByUsername = `-- name: GetAuthParamsByUsername :one
SELECT username, kdf FROM users WHERE username = $1
`

type GetAuthParamsByUsernameRow struct {
	Username string
	Kdf      []byte
}

func (q *Queries) GetAuthParamsByUsername(ctx context.Context, username string) (GetAuthParamsByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAuthParamsByUsername, username)
	var i GetAuthParamsByUsernameRow
	err := row.Scan(&i.Username, &i.Kdf)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT id, external_id, username, kdf, public_bundle, account_vault
FROM users WHERE id = $1
`

type GetUserAccountRow struct {
	ID           int64
	ExternalID   pgtype.UUID
	Username     string
	Kdf          []byte
	PublicBundle []byte
	AccountVault []byte
}

func (q *Queries) GetUserAccount(ctx context.Context, id int64) (GetUserAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserAccount, id)
	var i GetUserAccountRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.Kdf,
		&i.PublicBundle,
		&i.AccountVault,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, username, created_at
FROM users
WHERE external_id = $1
`

type GetUserByExternalIDRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Username   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID pgtype.UUID) (GetUserByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i GetUserByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentialsByUsername = `-- name: GetUserCredentialsByUsername :one
SELECT id, external_id, username, auth_credential_hash, created_at
FROM users
WHERE username = $1
`

type GetUserCredentialsByUsernameRow struct {
	ID                 int64
	ExternalID         pgtype.UUID
	Username           string
	AuthCredentialHash string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) GetUserCredentialsByUsername(ctx context.Context, username string) (GetUserCredentialsByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByUsername, username)
	var i GetUserCredentialsByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.AuthCredentialHash,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, external_id, username, created_at
FROM users
ORDER BY username, id
`

type ListUsersRow struct {
	ID         int64
	ExternalID pgtype.UUID
	Username   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
